In [3]:
import h5py
import numpy as np

In [71]:
for i in range(10):
    print(i)

    path = '/users/yewzzang/work/make_mc_vertex/analysis/mc_data_1207/positron_'+str(i+1)+'MeV.h5'
    output_name ='/users/yewzzang/work/make_mc_vertex/analysis/mc_data_0105/positron_'+str(i+1)+'MeV.h5'

    file = h5py.File(path,'r')

    out_jade_vertex = np.array(file['events']['jade_vertex'])
    out_vertex = np.array(file['events']['vertex'])
    out_pmtQ = np.array(file['events']['pmtQ'])
    out_energy = ((i+1)*np.ones(out_pmtQ.shape[0])).reshape(-1,1)
    print(out_energy)
    kwargs = {'dtype':'f4', 'compression':'lzf'}
    #     with h5py.File(output_path, 'w', libver='latest', swmr=True) as fout:

    with h5py.File(output_name, 'w', libver='latest', swmr=True) as fout:
        g = fout.create_group('events')

        g.create_dataset('pmtQ', data=out_pmtQ, chunks=(1,96,1),**kwargs)
        g.create_dataset('jade_vertex', data=out_jade_vertex, chunks=(1,3),**kwargs)
        g.create_dataset('vertex', data=out_vertex, chunks=(1,3),**kwargs)
        g.create_dataset('energy', data=out_energy, chunks=(1,1),**kwargs)

0
[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]]
1
[[2.]
 [2.]
 [2.]
 ...
 [2.]
 [2.]
 [2.]]
2
[[3.]
 [3.]
 [3.]
 ...
 [3.]
 [3.]
 [3.]]
3
[[4.]
 [4.]
 [4.]
 ...
 [4.]
 [4.]
 [4.]]
4
[[5.]
 [5.]
 [5.]
 ...
 [5.]
 [5.]
 [5.]]
5
[[6.]
 [6.]
 [6.]
 ...
 [6.]
 [6.]
 [6.]]
6
[[7.]
 [7.]
 [7.]
 ...
 [7.]
 [7.]
 [7.]]
7
[[8.]
 [8.]
 [8.]
 ...
 [8.]
 [8.]
 [8.]]
8
[[9.]
 [9.]
 [9.]
 ...
 [9.]
 [9.]
 [9.]]
9
[[10.]
 [10.]
 [10.]
 ...
 [10.]
 [10.]
 [10.]]
